### ISSUE TITLE
[FEATURE] - Events

### ISSUE THREAD

**Issue by alexstan67** [sky-unlimited/wef_2023#119]
**Issue Description**
Suggested destinations are also depending on events that might occur on/near airports, such as aeronautical events, meetings, fly ins, ...

Therefore we need to add a new Model/Controller/view called Events.

**table structure**
- airport_id
- type
- start_date
- end_date
- image_link
- url

Events should be visible by signed in users.
Events should be created/updated only by users having the role `admin`.

Users can access on events (READ) on index and show.

**TODO LIST**

- [x] Create Model Event
- [x] Create Controller EventsController
- [x] Create the create view for admins
- [x] Create the update/delete view for admins
- [x] Create access to events searcher in the nav bar under `Search > Events`
- [x] Adapt the `Destination.rb/get_top_destinations` in order to promote airports that offer an event during the correct time frame (of course if airport in flyzone)
- [x] Create events seeds for development
- [x] Write tests

**linked issues**
Issue #120 should be closed before!

**Open questions**
- [ ] Should users be able to comment on events? I think yes...

**Comment by alexstan67** [comment]
Some sources:
- https://lagazettedelulm.fr/

**Comment by christinasugiono** [comment]
For the comment on events maybe we can put it as a separate issue ticket, the PR is already pretty big 🤭
